[pytest]
addopts = -s -v
python_files = test_*.py *_test.py
python_classes = Test*
python_functions = test_*

markers =
    ui: Маркирова для UI тестов
    smoke: Маркирова для смоук тестов
    regression: Маркирова для  регрессионныз тестов
    slow: Маркирова для медленных тестов
    critical: Маркировка для критичных тестов
    dashboard: Маркировка для тестов, связанных с рабочей панелью
    registration: Маркировка для тестов, связанных с регистрацией пользователей
    authorization: Маркировка для тестов, связанных с авторизацией пользователей
    courses: Маркировка для тестов, связанных с курсами
    regression: Маркировка для регрессионных тестов


